services:
  echo-app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_REGION: ""
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test-db
      MYSQL_USER: david
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: