name: Push to ECR

on:
  workflow_dispatch:
        
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          
      - name: Docker login to ECR
        env: 
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin \
            "$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com"

      - name: Build and Push Services
        env:
          AWS_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          chmod 700 ./scripts/build_and_push
          services="client server"
          for dir in $services; do
            ./scripts/build_and_push "$dir" "$AWS_ID"
          done
